import path from 'node:path'
import vue from '@vitejs/plugin-vue'
import Unocss from 'unocss/vite'
import AutoImport from 'unplugin-auto-import/vite'
import IconsResolver from 'unplugin-icons/resolver'
import Icons from 'unplugin-icons/vite'
import { ElementPlusResolver } from 'unplugin-vue-components/resolvers'
import Components from 'unplugin-vue-components/vite'
import { defineConfig } from 'vite'

export default defineConfig({
  resolve: {
    alias: {
      '@': path.resolve(__dirname, 'src'),
    },
  },
  server: {
    port: 7788,
    cors: true,
    proxy: {
      '/api': {
        target: 'http://localhost:8888',
        changeOrigin: true,
        rewrite: path => path.replace(/^\/api/, ''),
      },
    },
  },
  css: {
    preprocessorOptions: {
      scss: {
        additionalData: `@use "@/styles/element/index.scss" as *;`,
      },
    },
  },
  plugins: [
    vue(),
    Unocss(),
    AutoImport({
      imports: [
        'vue',
        'vue-router',
        'pinia',
        '@vueuse/core',
        { axios: [['default', 'axios']] },
        { from: 'element-plus', imports: ['ElMessageBox', 'ElMessage', 'ElLoading', 'ElNotification'] },
        { from: 'element-plus', imports: ['FormInstance', 'FormRules', 'UploadFile'], type: true },
        { from: 'axios', imports: ['AxiosPromise'], type: true },
      ],
      resolvers: [
        ElementPlusResolver({ importStyle: 'sass' }),
        IconsResolver({ prefix: 'i' }),
      ],
      dirs: [
        'src/utils',
        'src/stores',
        'src/api/**',
        { glob: 'src/api/**', types: true },
      ],
      dts: 'auto-imports.d.ts',
    }),
    Components({
      resolvers: [
        ElementPlusResolver({ importStyle: 'sass' }),
        IconsResolver({ enabledCollections: ['ep'] }),
      ],
      dirs: ['src/components'],
      extensions: ['vue', 'jsx', 'tsx'],
      include: [/\.vue$/, /\.vue\?vue/],
      dts: 'components.d.ts',
    }),
    Icons({
      compiler: 'vue3',
      scale: 1.25,
    }),
  ],
  build: {
    emptyOutDir: true,
    outDir: '../resources/templates',
  },
  optimizeDeps: {
    include: [
      'vue',
      'vue-router',
      'pinia',
      'axios',
      'dayjs',
      'file-saver',
      '@iconify/vue',
      '@vueuse/core',
      'element-plus/es',
      'element-plus/es/locale/lang/zh-cn',
      'element-plus/es/components/affix/style/index',
      'element-plus/es/components/alert/style/index',
      'element-plus/es/components/anchor/style/index',
      'element-plus/es/components/anchor-link/style/index',
      'element-plus/es/components/aside/style/index',
      'element-plus/es/components/autocomplete/style/index',
      'element-plus/es/components/avatar/style/index',
      'element-plus/es/components/backtop/style/index',
      'element-plus/es/components/badge/style/index',
      'element-plus/es/components/base/style/index',
      'element-plus/es/components/breadcrumb/style/index',
      'element-plus/es/components/breadcrumb-item/style/index',
      'element-plus/es/components/button/style/index',
      'element-plus/es/components/button-group/style/index',
      'element-plus/es/components/calendar/style/index',
      'element-plus/es/components/card/style/index',
      'element-plus/es/components/carousel/style/index',
      'element-plus/es/components/carousel-item/style/index',
      'element-plus/es/components/cascader/style/index',
      'element-plus/es/components/cascader-panel/style/index',
      'element-plus/es/components/check-tag/style/index',
      'element-plus/es/components/checkbox/style/index',
      'element-plus/es/components/checkbox-button/style/index',
      'element-plus/es/components/checkbox-group/style/index',
      'element-plus/es/components/col/style/index',
      'element-plus/es/components/collapse/style/index',
      'element-plus/es/components/collapse-item/style/index',
      'element-plus/es/components/collapse-transition/style/index',
      'element-plus/es/components/color-picker/style/index',
      'element-plus/es/components/config-provider/style/index',
      'element-plus/es/components/container/style/index',
      'element-plus/es/components/countdown/style/index',
      'element-plus/es/components/date-picker/style/index',
      'element-plus/es/components/descriptions/style/index',
      'element-plus/es/components/descriptions-item/style/index',
      'element-plus/es/components/dialog/style/index',
      'element-plus/es/components/divider/style/index',
      'element-plus/es/components/drawer/style/index',
      'element-plus/es/components/dropdown/style/index',
      'element-plus/es/components/dropdown-item/style/index',
      'element-plus/es/components/dropdown-menu/style/index',
      'element-plus/es/components/empty/style/index',
      'element-plus/es/components/footer/style/index',
      'element-plus/es/components/form/style/index',
      'element-plus/es/components/form-item/style/index',
      'element-plus/es/components/header/style/index',
      'element-plus/es/components/icon/style/index',
      'element-plus/es/components/image/style/index',
      'element-plus/es/components/image-viewer/style/index',
      'element-plus/es/components/infinite-scroll/style/index',
      'element-plus/es/components/input/style/index',
      'element-plus/es/components/input-number/style/index',
      'element-plus/es/components/input-tag/style/index',
      'element-plus/es/components/link/style/index',
      'element-plus/es/components/loading/style/index',
      'element-plus/es/components/main/style/index',
      'element-plus/es/components/mention/style/index',
      'element-plus/es/components/menu/style/index',
      'element-plus/es/components/menu-item/style/index',
      'element-plus/es/components/menu-item-group/style/index',
      'element-plus/es/components/message/style/index',
      'element-plus/es/components/message-box/style/index',
      'element-plus/es/components/notification/style/index',
      'element-plus/es/components/option/style/index',
      'element-plus/es/components/option-group/style/index',
      'element-plus/es/components/overlay/style/index',
      'element-plus/es/components/page-header/style/index',
      'element-plus/es/components/pagination/style/index',
      'element-plus/es/components/popconfirm/style/index',
      'element-plus/es/components/popover/style/index',
      'element-plus/es/components/popper/style/index',
      'element-plus/es/components/progress/style/index',
      'element-plus/es/components/radio/style/index',
      'element-plus/es/components/radio-button/style/index',
      'element-plus/es/components/radio-group/style/index',
      'element-plus/es/components/rate/style/index',
      'element-plus/es/components/result/style/index',
      'element-plus/es/components/row/style/index',
      'element-plus/es/components/scrollbar/style/index',
      'element-plus/es/components/segmented/style/index',
      'element-plus/es/components/select/style/index',
      'element-plus/es/components/select-v2/style/index',
      'element-plus/es/components/skeleton/style/index',
      'element-plus/es/components/skeleton-item/style/index',
      'element-plus/es/components/slider/style/index',
      'element-plus/es/components/space/style/index',
      'element-plus/es/components/statistic/style/index',
      'element-plus/es/components/step/style/index',
      'element-plus/es/components/steps/style/index',
      'element-plus/es/components/sub-menu/style/index',
      'element-plus/es/components/switch/style/index',
      'element-plus/es/components/tab-pane/style/index',
      'element-plus/es/components/table/style/index',
      'element-plus/es/components/table-column/style/index',
      'element-plus/es/components/table-v2/style/index',
      'element-plus/es/components/tabs/style/index',
      'element-plus/es/components/tag/style/index',
      'element-plus/es/components/teleport/style/index',
      'element-plus/es/components/text/style/index',
      'element-plus/es/components/time-picker/style/index',
      'element-plus/es/components/time-select/style/index',
      'element-plus/es/components/timeline/style/index',
      'element-plus/es/components/timeline-item/style/index',
      'element-plus/es/components/tooltip/style/index',
      'element-plus/es/components/tour/style/index',
      'element-plus/es/components/tour-step/style/index',
      'element-plus/es/components/transfer/style/index',
      'element-plus/es/components/tree/style/index',
      'element-plus/es/components/tree-select/style/index',
      'element-plus/es/components/tree-v2/style/index',
      'element-plus/es/components/upload/style/index',
      'element-plus/es/components/virtual-list/style/index',
      'element-plus/es/components/watermark/style/index',
    ],
  },
})
