server:
  port: 9990

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      maximum-pool-size: 20
      minimum-idle: 10
      connectionTimeout: 30000
      validationTimeout: 5000
      idleTimeout: 600000
      maxLifetime: 1800000
      connectionTestQuery: SELECT 1
      keepaliveTime: 30000
    url: jdbc:mysql://localhost:3306/sijay?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  data:
    redis:
      database: 2
      host: 127.0.0.1
      port: 6379
      # password:
      timeout: 10s
      lettuce:
        pool:
          max-active: 200
          max-wait: -1ms
          max-idle: 10
          min-idle: 0
  jpa:
    open-in-view: false
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
    add-properties: false
  main:
    banner-mode: off
  profiles:
    active: default

# Sa-Token配置
sa-token:
  token-name: Authorization
  timeout: 604800
  is-concurrent: true
  is-share: false
  jwt-secret-key: thisisajwtsecretprivatekey
  is-read-body: true
  is-read-header: true
  is-read-cookie: false
logging:
  level:
    web: info

