spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      maximum-pool-size: 20
      minimum-idle: 10
      connectionTimeout: 30000
      validationTimeout: 5000
      idleTimeout: 600000
      maxLifetime: 1800000
      connectionTestQuery: SELECT 1
      keepaliveTime: 30000
    url: jdbc:mysql://localhost:3306/sijay?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  sql:
    init:
      data-locations: classpath:data/data.sql
      schema-locations: classpath:data/schema.sql
      encoding: utf-8
      #      mode: always
      username: root
      password: root
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true


# Sa-Token配置
sa-token:
  token-name: Authorization
  timeout: 604800
  is-concurrent: true
  is-share: false
  jwt-secret-key: thisisajwtsecretprivatekey
  is-read-body: true
  is-read-header: true
  is-read-cookie: false
  token-prefix: "Bearer"
