server:
  port: 12333
  servlet:
    context-path:

logging:
  level:
    root: @logging.level@
  pattern:
    console: "%green(%d{HH:mm:ss}) %highlight(%-5level) %magenta(%logger{100}%n) %msg%n"
  charset:
    console: utf-8

springdoc:
  writer-with-default-pretty-printer: true
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/suap?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      connectionTimeout: 30000
      validationTimeout: 5000
      idleTimeout: 600000
      maxLifetime: 1800000
      connectionTestQuery: SELECT 1
      keepaliveTime: 30000
  data:
    # redis配置
    redis:
      # Redis数据库索引（默认为0）
      database: 3
      # Redis服务器地址
      host: localhost
      # Redis服务器连接端口
      port: 6379
      # Redis服务器连接密码（默认为空）
      # password:
      # 连接超时时间
      timeout: 10s
      lettuce:
        pool:
          # 连接池最大连接数
          max-active: 200
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
          # 连接池中的最大空闲连接
          max-idle: 10
          # 连接池中的最小空闲连接
          min-idle: 0
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
  jackson:
    # 日期格式化
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
    serialization:
      # 忽略无法转换的对象
      fail_on_empty_beans: false
    deserialization:
      # 允许对象忽略json中不存在的属性
      fail_on_unknown_properties: false
    parser:
      allow-unquoted-control-chars: true
      allow-single-quotes: true
    locale: zh_CN
  #devtools热部署
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  main:
    banner-mode: off
  profiles:
    active: dev
  application:
    name: Simple Unified Application Platform

############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: tk
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: simple-uuid
  # 是否输出操作日志
  is-log: true

config:
  # 密码最大错误次数
  passwordMaxRetryCount: 5
  # 密码锁定时间（默认10分钟）
  passwordLockTime: 10
  tokenTimeout: 60
  tempFolder: temp
  fileStorage: file

doc:
  title: ${suap.name}
  description: ${suap.desc}
  contact: ${user.name}
  version: ${revision}

gen:
  # 代码生成路径
  path: code
  # 作者
  author: ${user.name}
  # 模板类型 cn.sijay.suap.core.enums.TemplateType
  template: '列表'
  # 包路径
  packageName: 'cn.sijay.suap'
  # 生成方式 cn.sijay.suap.core.enums.GenType
  genType: '压缩包'

