spring:
  datasource:
    url: jdbc:h2:file:./db/h2
    driver-class-name: org.h2.Driver
    username: root
    password: root
  h2:
    console:
      enabled: true
      path: /h2_console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      data-locations: classpath:data/data.sql
      schema-locations: classpath:data/schema.sql
      encoding: utf-8
      mode: always
