# 日志配置
logging:
  level:
    root: info
    p6spy: info
  pattern:
    console: "%red(%d{yyyy-MM-dd HH:mm:ss}) %green([%thread]) %highlight(%-5level) %boldMagenta(%logger%n) - %msg%n"
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
  jpa:
    open-in-view: true
decorator:
  datasource:
    p6spy:
      multiline: false
      log-format: "%(sql)"