/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    401: typeof import('./src/components/401.vue')['default']
    404: typeof import('./src/components/404.vue')['default']
    Breadcrumb: typeof import('./src/components/Breadcrumb.vue')['default']
    BuildCode: typeof import('./src/components/BuildCode.vue')['default']
    DictTag: typeof import('./src/components/DictTag.vue')['default']
    Editor: typeof import('./src/components/Editor.vue')['default']
    FileUpload: typeof import('./src/components/FileUpload.vue')['default']
    Hamburger: typeof import('./src/components/Hamburger.vue')['default']
    HeaderSearch: typeof import('./src/components/HeaderSearch.vue')['default']
    IconSelect: typeof import('./src/components/IconSelect.vue')['default']
    IFrame: typeof import('./src/components/IFrame.vue')['default']
    ImagePreview: typeof import('./src/components/ImagePreview.vue')['default']
    ImageUpload: typeof import('./src/components/ImageUpload.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    ParentView: typeof import('./src/components/ParentView.vue')['default']
    Redirect: typeof import('./src/components/Redirect.vue')['default']
    Render: typeof import('./src/components/Render.vue')['default']
    RightToolbar: typeof import('./src/components/RightToolbar.vue')['default']
    RoleSelect: typeof import('./src/components/RoleSelect.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScreenFull: typeof import('./src/components/ScreenFull.vue')['default']
    SizeSelect: typeof import('./src/components/SizeSelect.vue')['default']
    STable: typeof import('./src/components/STable.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    TopNav: typeof import('./src/components/TopNav.vue')['default']
    TreeSelect: typeof import('./src/components/TreeSelect.vue')['default']
    UserSelect: typeof import('./src/components/UserSelect.vue')['default']
  }
}
